#!/bin/bash

user=$(whoami)

echo "Você está logado como: $user " 

echo -n "Joga um numero ai:" 

read var

echo -n "Quer comparar com qual numero: "

read var1

#echo ${var}

if [[ $var -gt $var1 ]]
then
	echo 'Primeiro numero é maior'
elif [[ $var -eq $var1 ]]
then
	echo 'Ambos os numeros são iguais'
else 
	echo 'Segundo numero é menor'
fi 

