#!/usr/bin/env bash

clear 
echo "Information very important !" 
echo "----------------------------"

echo -n "User "
whoami

echo -n "Hostname: "
hostname 

echo -n "Uptime: "
uptime -p

echo -n "Kernel: "
uname -rms

echo  "-----------------------------"  


