services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - '8999:8080'
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    restart: unless-stopped
  
  openvpn-exporter:
    image: kumina/openvpn-exporter:latest
    container_name: openvpn-exporter
    ports:
      - "9176:9176"
    volumes:
      - /etc/openvpn:/etc/openvpn:ro
    restart: unless-stopped
    command:
      - '--openvpn.status_paths=/etc/openvpn/openvpn-status.log'
  
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    ports:
      - "8000:8000"  # Port for Portainer agent communication
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  redis:
    image: redis:latest
    platform: linux/amd64
    command: >
      sh -c 'REDIS_PASS=$(cat /run/secrets/redis_password) && redis-server --requirepass "$REDIS_PASS"'
    ports:
      - "6379:6379"
    secrets:
      - redis_password

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://${HOST_IP}:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - ./waha/sessions:/app/.sessions
      - ./waha/media:/app/.media
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    environment:
      WEBHOOK_URL: http://${HOST_IP}:5678
      N8N_HOST: ${HOST_IP}
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    volumes:
      - ./n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  portainer_data:
    driver: local
    external: true

secrets:
  redis_password:
    file: ./secrets/redis_password.txt